Algoritmo "Operadores Aritmeticos"

// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcos Nogueira
// Data atual  : 20/10/2020
Var
// Seção de Declarações das variáveis 
   resultado, valor1, valor2, valor3: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   valor1:= 10
   valor2:= 10
   valor3:= 10
   resultado:= ((valor1 + valor2 + valor2) / valor3) %  2
   escreval("Resultado: ", resultado)
Fimalgoritmo