Algoritmo "Operadores relacioais"
/
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcos Nogueira
// Data atual  : 20/10/2020
Var
// Seção de Declarações das variáveis 
nota1, nota2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nota1 := 10
nota2 := 15

se(nota1 <> nota2)entao
         escreval("Nota1 é diferente")
senao
     escreval ("Nota1 é igual")
fimse


Fimalgoritmo